# Generated by Django 2.2.5 on 2021-04-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210227_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('other', 'Other'), ('male', 'Male')], max_length=10),
        ),
    ]
