# Generated by Django 2.2.5 on 2021-04-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20210405_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
    ]
