# Generated by Django 2.2.5 on 2021-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20210406_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
    ]
