# Generated by Django 2.2.5 on 2021-06-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20210608_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
    ]
